version: '3.8'

services:
  td-postgres:
    image: postgres:15
    container_name: db
    environment:
     - POSTGRES_DB=tdstats
     - POSTGRES_USER=td
     - POSTGRES_PASSWORD=td
    ports:
    - '5432:5432'
    volumes:
    - pg_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=DEBUG
      - DATABASE_URL=postgresql://td:td@td-postgres/tdstats?conn_max_age=600
      - WAREHOUSE_URL=${WAREHOUSE_URL}
      - ALLOWED_HOST=*
      - ADMIN_SLUG=plop
      - MESSAGE_RECIPIENTS="bill@example.com"
    depends_on:
      - td-postgres


volumes:
  pg_data:

